### ISSUE TITLE
Exception "unable to resolve class de.interactive_instruments.xtf.Util"

### ISSUE THREAD

**Issue by heidivanparys** [Geonovum/etf-test-projects-inspire#3]
I set up SoapUI to run the ETF tests by following the guidelines on http://www.geonovum.nl/validator-inspire-view-en-downloadservices. I get the following exception in test case Update Credentials: unable to resolve class de.interactive_instruments.xtf.Util, caused by an import statement in the script of the test case

![class_de interactive_instruments xtf util](https://cloud.githubusercontent.com/assets/11427611/11236674/80b5027c-8ddb-11e5-9d97-5aa6bb2cbeac.png)

Where can I find the jar file that contains class de.interactive_instruments.xtf.Util and how do I add it as a dependency to my SoapUI project?

Note: the reasons I am running the tests through SoapUI and not through the online validator, are that
- The services I am testing is protected with a username and password, that have to be given through two extra parameters to each service call. I followed the guidelines in section 4.2.3 of the aformentioned guidelines to add these parameters to every service call.
- The service is set up using Go Publisher which does not support parameter outputFormat in service requests, see also https://wiki.snowflakesoftware.com/display/GP30DOC/Standard+Presentation+Parameters, so I removed this parameter from the service calls where it was used.

![request_parameters](https://cloud.githubusercontent.com/assets/11427611/11237037/986739e2-8ddd-11e5-85c1-6f4ed7809d61.png)

**Comment by heidivanparys** [comment]
@cportele Could you please have a look at this issue?

**Comment by jonherrmann** [comment]
Download the required libraries from https://services.interactive-instruments.de/etfdev-af/etf-public-releases/de/interactive-instruments/etf/etf-owsgtl-1.3.2.zip. If you are asked for a login use: etf-public-releases/etf-public-releases. Afterwards copy the content of the zip to the bin/ext sub folder of your SoapUI installation directory.

**Comment by heidivanparys** [comment]
Great, that solved the error, thanks.
