### ISSUE TITLE
WFS: DescribeFeatureType: typename or typenames in KVP encoding?

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/etf-test-projects-inspire#31]
WFS 2.0.0 specifies for DescribeFeatureType KVP encoding to use the parameter name "typenames", see section 9.2.4.1. Although there is also a table using "typename". Which should be used in the requests?

Edit: in WFS 2.0.2 this also occurs: http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#149

**Comment by thijsbrentjens** [comment]
This is relevant for many implementations in NL (from PDOK for example), where the parameter is only accepted if the keyword "typename" is used. When using "typenames", the DescribeFeatureType request returns schemas for ALL featuretypes

**Comment by cportele** [comment]
@thijsbrentjens 
TYPENAMES is correct: "For KVP-encoded requests the typeNames parameter shall be encoded using the TYPENAMES keyword", see http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#149. 

The use of TYPENAME in table 15 is an error that needs to be fixed in the WFS standard (@pvretano). Probably this is a leftover from WFS 1.x, where it was TYPENAME.

**Comment by thijsbrentjens** [comment]
Okay, clear. Nasty detail for some implementations I guess.

For now: I can imagine we will have discussions on this when testing: both are still found in the standard. 
So I tested sing both (typename=<featuretypename>&typenames=<featuretypename>) now, to use in a DescribeFeatureType request. This works (and avoids for a service offering more than 500 featuretypes that we will retrieve all schemas every request). It is a bit more relaxed than it should be, what do you think about this?

(I'll create a pull request, you'll see the changes)

**Comment by cportele** [comment]
Yes, that makes sense as we have both parameter names in the standard at the moment.

**Comment by thijsbrentjens** [comment]
I'll merge the pull request then.
