### ISSUE TITLE
Should parameter valuereference have a namespace prefix?

### ISSUE THREAD

**Issue by heidivanparys** [Geonovum/etf-test-projects-inspire#5]
Parameter valuereference in the WFS test suite, test case _Minimum Standard Filter - Optional_, test step _GetPropertyValue_ currently does not have a namespace prefix: request parameter valuereference is set to ${#TestSuite#FirstTextualProperty}

![getpropertyvalue_valuereference](https://cloud.githubusercontent.com/assets/11427611/11270048/e0963aae-8ebb-11e5-846f-607bb0744203.png)

In the service I'm testing, the first textual property is gn:beginLifespanVersion (it is not plain text but a date in fact).

``` xml
<wfs:FeatureCollection>
   <wfs:member>
      <elf-gn:NamedPlace gml:id="dk.gn.1233766a-1067-6b98-e053-d480220a5a3f">
         <gn:beginLifespanVersion>2015-03-26T16:48:13.000</gn:beginLifespanVersion>
      [...]
      </elf-gn:NamedPlace>
   </wfs:member>
</wfs:FeatureCollection>
```

so I would expect a valid XPath expression in the context of elf-gn:NamedPlace to be `gn:beginLifespanVersion` and not `beginLifespanVersion`.

This can be achieved in different ways:
- by setting parameter valuereference to ${#TestSuite#FeatureTypeNamespacePrefix}:${#TestSuite#FirstTextualProperty}
- by using XPath function name instead of local-name in the process of setting property FirstTextualProperty (a consequence of this change would be that the parameter filter in test step _GetFeatureWithPropertyIsEqualTo_ is updated too, since that parameter currently contains `<fes:ValueReference>${#TestSuite#FeatureTypeNamespacePrefix}:${#TestSuite#FirstTextualProperty}</fes:ValueReference>`)

![propertytransfervaluereference](https://cloud.githubusercontent.com/assets/11427611/11269869/70562110-8eba-11e5-811e-f06e1e28f825.png)

When looking at this issue, I looked at the WFS specification, and I am confused about one of the examples given in section 10.2.4.3, where it actually gives an example of a valueReference value not using a namespace, although the XML it is querying uses namespaces. I am wondering:
1. Is this a mistake in the WFS specification?
2. Or am I reading the XPath specification wrong? At least I cannot use beginLifespanVersion instead of gn:beginLifespanVersion when I test XPath expressions on the result of the GetFeature-operation using different XML editors.
3. Or does the WFS specification allow more "lax" expressions, meaning prefixes can be omitted?
4. Do certain WFS server implementations allow more "lax" expressions, meaning prefixes can be omitted?

![valuereference_wfs_2_0_0](https://cloud.githubusercontent.com/assets/11427611/11270129/96b7a25a-8ebc-11e5-9ba7-f69fd3cc4cb0.png)

**Comment by thijsbrentjens** [comment]
Hi, I think you have a good point here. The WFS spec might be wrong in the examples. 

I think you should be able to use gn:beginLifespanVersion. I've changed the test to include a namespace prefix in the GetPropertyValue request. Please reopen if this does not work as expected for you. 

For testing, if you have a publicly available service (URL) that would be helpful.
