### ISSUE TITLE
Metadata dataset

### ISSUE THREAD

**Issue by heidivanparys** [Geonovum/etf-test-projects-inspire#6]
The tests seems to treat the presence of svr:operatesOn (information on the datasets that the service operates on, ISO 19119) as obligatory, although svr:operatesOn is conditional to services: Mandatory if linkage to datasets on which the service operates are available (see also http://inspire.jrc.ec.europa.eu/documents/Metadata/MD_IR_and_ISO_20131029.pdf).

This results in an exception in the test when svr:operatesOn is not present:

![missing_endpoint_for_request_getmetadatadatasetfromservicemetadata](https://cloud.githubusercontent.com/assets/11427611/11367704/bfc2dd02-92b5-11e5-95ac-ff624a3a68df.png)

```
Tue Nov 24 13:24:21 CET 2015:INFO:Got response for [Req 42 (Scenario 1) ExternalServiceMetadata] in 27ms (14543 bytes)
Tue Nov 24 13:24:38 CET 2015:ERROR:Exception during Test Execution
   java.lang.NullPointerException
    at com.eviware.soapui.impl.wsdl.teststeps.HttpTestRequestStep.run(HttpTestRequestStep.java:264)
    at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.runTestStep(AbstractTestCaseRunner.java:211)
    at com.eviware.soapui.impl.wsdl.testcase.WsdlTestCaseRunner.runCurrentTestStep(WsdlTestCaseRunner.java:47)
    at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.internalRun(AbstractTestCaseRunner.java:138)
    at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.internalRun(AbstractTestCaseRunner.java:46)
    at com.eviware.soapui.impl.wsdl.support.AbstractTestRunner.run(AbstractTestRunner.java:129)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by thijsbrentjens** [comment]
Hi, this is for the Download Services tests for WFS implementations, correct?

srv:operatesOn itself is optional indeed. But for the test we assume that the Download Services offers data and because INSPIRE requires datasets to be described in metadata, there must also be a metadata record describing the dataset. So there must always be at least one srv:operatesOn element.

Do you have a case where this is not valid? Please let it know then.

**Comment by heidivanparys** [comment]
This issue indeed concerns the test for a WFS.

Thanks for the explanation, I updated the metadata of the WFS I was testing so it now has an srv:operatesOn element.

I would like to suggest an update of the test case "Mandatory INSPIRE GetCapabilities" to make the requirements regarding the coupled resource(s) more explicit.

As far as I can see (but I'm no SoapUI expert), the following changes could help with this:
1. Add the assertion that at least one coupled resource must be available in the metadata of the WFS to test step "Req 42 (Scenario 1) ExternalServiceMetadata".
2. Add the assertion that the specified coupled resources must be defined by reference to test step "Req 42 (Scenario 1) ExternalServiceMetadata" (implementation of test https://github.com/inspire-eu-validation/ats-metadata/blob/master/A.29.IR07.srv.identification.md).
3. Update test step "RunMetadataDatasetFromServiceMetadata" so test step "GetMetadataDatasetFromServiceMetadata" is only run from within test step "RunMetadataDatasetFromServiceMetadata" and not as a separate step in the test case execution.

Change 1 would be something like this:

``` XQuery
declare namespace gmd='http://www.isotc211.org/2005/gmd';
declare namespace csw='http://www.opengis.net/cat/csw/2.0.2';
declare namespace srv='http://www.isotc211.org/2005/srv';

<result>AssertionFailures: {
let $value:=//gmd:MD_Metadata/gmd:identificationInfo/srv:SV_ServiceIdentification/srv:operatesOn
return
if (exists($value))
then "A coupled resource (srv:operatesOn) is available in the metadata of the WFS"
else "A coupled resource (srv:operatesOn) is not available in the metadata of the WFS"
}
</result>
```

Change 2 would be something like this:

``` XQuery
declare namespace gmd='http://www.isotc211.org/2005/gmd';
declare namespace csw='http://www.opengis.net/cat/csw/2.0.2';
declare namespace srv='http://www.isotc211.org/2005/srv';
declare namespace xlink='http://www.w3.org/1999/xlink';

<result>AssertionFailures: {
let $value:=count(//gmd:MD_Metadata/gmd:identificationInfo/srv:SV_ServiceIdentification/srv:operatesOn) = count(//gmd:MD_Metadata/gmd:identificationInfo/srv:SV_ServiceIdentification/srv:operatesOn/@xlink:href)
return
if ($value)
then "The coupled resources in the metadata of the WFS are defined by reference (xlink:href)"
else "The coupled resources in the metadata of the WFS are not defined by reference (xlink:href)"
}
</result>
```

Change 3 would be adding the following line at the end of the script in test step "RunMetadataDatasetFromServiceMetadata":

``` Groovy
testRunner.gotoStepByName("Property Transfer (Finish Goto)");
```

Explanation: in the following cases:
- no srv:operatesOn is present at all
- srv:operatesOn is present but does not contain a xlink:href attribute (e.g. only attribute uuidref is present, this is e.g. the case when using the GUI of GeoNetwork 2.6.4 for maintaining metadata)

the following happens in test step "RunMetadataDatasetFromServiceMetadata":
- no metadataUrlNodes are found
- property value urlToTest is never changed to anything else than an empty string
- the next test step in line after test step "RunMetadataDatasetFromServiceMetadata" is "GetMetadataDatasetFromServiceMetadata", which fails with a NullPointerException, and the error "Missing endpoint for request [GetMetadataDatasetFromServiceMetadata]" is displayed to the user.

In the case that srv:operatesOn is present and does contain a xlink:href attribute, then test step "GetMetadataDatasetFromServiceMetadata" is probably run twice for one of the //srv:operatesOn/@xlink:href nodes, once from within test step "RunMetadataDatasetFromServiceMetadata" and once because it is the next test step in line.

**Comment by thijsbrentjens** [comment]
Thanks for these suggestions, really nice and detailed! I'm putting them into the test project now. With some small changes in the XQuery code.

If you know of a publicly available service (with metadata) I could test on, like the one you are mentioning above, that would be really helpful.

**Comment by thijsbrentjens** [comment]
Created a pull request for the proposed changes, https://github.com/Geonovum/etf-test-projects-inspire/pull/11. @heidivanparys feel free to comment on the pull request. If you don't have any comments, I'll merge it.

**Comment by heidivanparys** [comment]
@thijsbrentjens 
You can use the following services for testing:
- http://kortforsyningen.kms.dk/gn_elf_gml321?service=WFS&request=GetCapabilities (svr:operatesOn present but not xlink:href)
- http://kortforsyningen.kms.dk/au_elf_gml321?service=WFS&request=GetCapabilities (svr:operatesOn not present at all)

**Comment by thijsbrentjens** [comment]
Thanks for the test cases. 

It works now as you proposed, I hope:
1) if no xlink:href is provided, the assertion to check for a reference fails
2) if no srv:operatesOn is not present at all, the assertion to check for operatesOn fails. 

In both cases, the error "Missing endpoint for request [GetMetadataDatasetFromServiceMetadata]"  is not shown to the user anymore. But the report contains a nicer and more precise message what is going wrong.

The code is already in the repo. The validator you ran the test with (for ELF?), needs an update to get these changes I think.

If this is not what you expected, please reopen this issue.

**Comment by jonherrmann** [comment]
@thijsbrentjens @heidivanparys 
I updated the ELF validator http://services.interactive-instruments.de/etf-demo-1-e/
