### ISSUE TITLE
WMS M-CR-V01: no assertion which checks for exception reports in test step "GetCapabilities"

### ISSUE THREAD

**Issue by jonherrmann** [Geonovum/etf-test-projects-inspire#63]
Example:

```
<ExceptionReport xmlns="http://www.opengis.net/ows/1.1">
<Exception code="NoApplicableCode">
<ExceptionText>
<![CDATA[
No other exceptionCode specified by this service and server applies to this exception.
]]>
</ExceptionText>
</Exception>
</ExceptionReport>
```

**Comment by thijsbrentjens** [comment]
What do you mean exactly? That there should be a test that Capabilities are returned? The test step "getCapabilities" contains a test for existence of  /wms:WMS_Capabilities. So it should fail somehow.

**Comment by jonherrmann** [comment]
The Test Case "Test Mandatory WMS GetCapabilities Parameters" will pass where "Test Mandatory INSPIRE Get View Service Metadata and Link View Service" fails:

<img width="614" alt="screen shot 2016-07-14 at 21 19 57" src="https://cloud.githubusercontent.com/assets/13570741/16852551/ddab0834-4a08-11e6-9861-08edd00fd424.png">

When you take the response above and run the XQuery assertion against it:

```
declare namespace wms='http://www.opengis.net/wms';

<result>AssertionFailures:
{
for $obj in /wms:WMS_Capabilities
let $nm:=$obj/@version
where $nm!='1.3.0'
return concat(" version should be 1.3.0, but version in WMS Capabilities is: ", data($nm))
}
</result>
```

you get the "expected" result:
`<result>AssertionFailures:</result>`

**Comment by thijsbrentjens** [comment]
That needs a fix indeed....
