### ISSUE TITLE
credentials not valid

### ISSUE THREAD

**Issue by Harm-Olthof** [Geonovum/etf-test-projects-inspire#79]
The credentials for https://services.interactive-instruments.de/etfdev-af/etf-public-releases/de/interactive-instruments/etf/  given in the readme don't seem to be valid anymore.

**Comment by jonherrmann** [comment]
We have reorganised the repository. Please use:
https://services.interactive-instruments.de/etfdev-af/etf-public-dev/de/interactive-instruments/etf/

with the credentials:
etf-public-dev / etf-public-dev

@thijsbrentjens this should be changed in the Readme
